package entities;
// Generated Oct 14, 2016 2:07:37 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Sekolah generated by hbm2java
 */
@Entity
@Table(name="sekolah"
    ,catalog="hibernate_db"
)
public class Sekolah  implements java.io.Serializable {


     private Integer id;
     private String npsn;
     private String namaSekolah;
     private String gugus;
     private String kabKota;
     private String alamat;

    public Sekolah() {
    }

	
    public Sekolah(String gugus, String kabKota, String alamat) {
        this.gugus = gugus;
        this.kabKota = kabKota;
        this.alamat = alamat;
    }
    public Sekolah(String npsn, String namaSekolah, String gugus, String kabKota, String alamat) {
       this.npsn = npsn;
       this.namaSekolah = namaSekolah;
       this.gugus = gugus;
       this.kabKota = kabKota;
       this.alamat = alamat;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="npsn", length=10)
    public String getNpsn() {
        return this.npsn;
    }
    
    public void setNpsn(String npsn) {
        this.npsn = npsn;
    }

    
    @Column(name="nama_sekolah", length=50)
    public String getNamaSekolah() {
        return this.namaSekolah;
    }
    
    public void setNamaSekolah(String namaSekolah) {
        this.namaSekolah = namaSekolah;
    }

    
    @Column(name="gugus", nullable=false, length=10)
    public String getGugus() {
        return this.gugus;
    }
    
    public void setGugus(String gugus) {
        this.gugus = gugus;
    }

    
    @Column(name="kab_kota", nullable=false, length=50)
    public String getKabKota() {
        return this.kabKota;
    }
    
    public void setKabKota(String kabKota) {
        this.kabKota = kabKota;
    }

    
    @Column(name="alamat", nullable=false, length=65535)
    public String getAlamat() {
        return this.alamat;
    }
    
    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }




}


